Various additions

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,7 +2,68 @@
 set -e
 shopt -s nullglob
 
-MAX_JOBS=32
+CPUS_TO_JOBS_FACTOR=2
+
+FREQS=(
+	day
+	mon
+)
+
+FREQS_ENS=(
+	mon
+	yr
+)
+
+STAGES=(
+	core
+	tier1
+)
+
+INPUT_VARS=(
+	tas
+	pr
+	psl
+	tasmin
+	tasmax
+)
+
+VARS=(
+	tas
+	pr
+	psl
+	tasmin
+	tasmax
+	su
+	gsstart
+)
+
+PERIODS=(
+	"1991 2020"
+    "2071 2100"
+)
+
+PERIOD_PAIRS=(
+	"1991 2020 2071 2100"
+)
+
+SEASONS=(
+	ANN
+	MAM
+	JJA
+	SON
+	DJF
+)
+
+REGIONS=(
+	BI
+	IP
+	FR
+	ME
+	SC
+	AL
+	MD
+	EA
+)
 
 LISTS=(
 	hclim_historical+ssp126
@@ -24,6 +85,7 @@ LISTS_INDICES=(
 
 LISTS_MAP_MEAN=(
 	hclim_historical+ssp126
+	gcm_historical+ssp126
 )
 
 LISTS_MAP_DIFF=(
@@ -46,6 +108,15 @@ LISTS_HEATMAP_TREND=(
 	hclim_historical+ssp126
 )
 
+LISTS_ARCHIVE=(
+	hclim_historical+ssp126
+)
+
+LISTS_CLIM_INDICES=(
+	obs
+	hclim_historical+ssp370
+)
+
 SUBTYPES=(
 	period_season
 	period_season_region
@@ -55,8 +126,13 @@ INDICES=(
 	sd
 )
 
-njobs=$(nproc)
-(( njobs > "$MAX_JOBS" )) && njobs=$MAX_JOBS
+ARCHIVE_VARS=(
+	tas
+	pr
+	psl
+	tasmin
+	tasmax
+)
 
 task=$1
 
@@ -71,8 +147,15 @@ cmd () {
 }
 
 run () {
+	njobs=$(("$(nproc)"/"$CPUS_TO_JOBS_FACTOR"))
+	[[ njobs == 0 ]] && njobs=1
 	# cat "$tmp"
-	parallel -tuj "$njobs" < "$tmp"
+	status=0
+	parallel -tuj "$njobs" < "$tmp" || status="$?"
+	if [[ $status != 0 ]]; then
+		echo "ERROR: parallel returned non-zero exit status $status" >&2
+		exit "$status"
+	fi
 	echo > "$tmp"
 }
 
@@ -83,7 +166,70 @@ calc_stats () {
 	local out=$4
 	mkdir -p "$out"
 	for source in $(cat "sources/list/${list}"); do
-		cmd bin/calc_stats "$subtype" "$input/$source"_mon "$source" "$out"
+		for period in "${PERIODS[@]}"; do
+			for season in "${SEASONS[@]}"; do
+				for var in "${VARS[@]}"; do
+					[[ ( $var == su || $var == gsstart ) && $season != ANN ]] \
+						&& continue
+					if [[ $subtype == "period_season_region" ]]; then
+						for region in "${REGIONS[@]}"; do
+							cmd bin/calc_stats \
+								"$input/$source" \
+								"$source" \
+								$period \
+								"$season" \
+								"$region" \
+								"$var" \
+								"$out"
+						done
+					else
+						cmd bin/calc_stats \
+							"$input/$source" \
+							"$source" \
+							$period \
+							"$season" \
+							"$var" \
+							"$out"
+					fi
+				done
+			done
+		done
+	done
+}
+
+plot_map () {
+	local args=("$@")
+	local type_=${args[0]}
+	local in=${args[1]}
+	local out=${args[2]}
+	local sources=${args[@]:3}
+	mkdir -p "$out"
+	for var in "${VARS[@]}"; do
+		for season in "${SEASONS[@]}"; do
+			if [[ $type_ == diff ]]; then
+				for period in "${PERIOD_PAIRS[@]}"; do
+					cmd bin/plot_map \
+						"$type_" \
+						"$var" \
+						"$season" \
+						$period \
+						"$in" \
+						$sources \
+						"$out"
+				done
+			else
+				for period in "${PERIODS[@]}"; do
+					cmd bin/plot_map \
+						"$type_" \
+						"$var" \
+						"$season" \
+						$period \
+						"$in" \
+						$sources \
+						"$out"
+				done
+			fi
+		done
 	done
 }
 
@@ -113,7 +259,7 @@ Tasks:
   remap_obs             Remap observatiosn to a 1x1 degree grid for GCM calculations.
   calc_ensembles        Calculate model ensembles.
   calc_stats            Calculate statistics (dep: source_links, remap_landmask, remap_obs, ensemble).
-  calc_indices          Calculate climate indices.
+  calc_clim_indices     Calculate climate indices.
   calc_model_ranking    Calculate model ranking (dep: calc_stats).
   plot_map_mean         Plot maps for means (dep: calc_stats).
   plot_map_diff         Plot maps for differences between time periods (dep: calc_stats).
@@ -130,25 +276,39 @@ Tasks:
   download_topo         Download topography.
   remap_topo            Remap topography (dep: download_topo).
   plot_domain_map       Plot domain map (dep: remap_topo).
+  archive               Prepare an archive of input data.
 EOF
 	;;
 
 source_links)
-	out=input/sources
-	mkdir -p "$out"
-	while read -r line; do
-		items=($line)
-		name=${items[0]}
-		out1=$out/$name
-		mkdir -p "$out1"
-		for path in ${items[@]:1}; do
-			for file in "$path"/*.nc; do
-				if [ -e "$file" ]; then
-					cmd ln -fs "$file" -t "$out1/"
-				fi
+	out=data/sources
+	for file in sources/paths/*; do
+		while read -r line; do
+			for stage in "${STAGES[@]}"; do
+				for freq in "${FREQS[@]}"; do
+					for var in "${INPUT_VARS[@]}"; do
+						s=$(echo "$line" | \
+							stage=$stage \
+							freq=$freq \
+							var=$var \
+							envsubst \
+						)
+						items=($s)
+						name=${items[0]}
+						out1=$out/$name/$freq/$var
+						for path in ${items[@]:1}; do
+							for file in "$path/${var}_"*.nc; do
+								if [ -e "$file" ]; then
+									mkdir -p "$out1"
+									cmd ln -fs "$file" -t "$out1/"
+								fi
+							done
+						done
+					done
+				done
 			done
-		done
-	done < "sources/paths"
+		done < "$file"
+	done
 	;;
 
 remap_landmask)
@@ -161,42 +321,57 @@ remap_landmask)
 	;;
 
 remap_obs)
-	for obs in $(cat sources/list/obs); do
-		out=data/1deg/$obs
-		mkdir -p "$out"
-		for file in "input/sources/$obs"/*; do
-			cmd cdo \
-				remapbil,r360x180 \
-				"$file" \
-				"$out/$(basename "$file")"
+	for source in $(cat sources/list/obs); do
+		for freq in "${FREQS[@]}"; do
+			for var in "${VARS[@]}"; do
+				out=data/1deg/$source/$freq/$var
+				for file in "data/sources/$source/$freq/$var/"*.nc; do
+					mkdir -p "$out"
+					cmd cdo \
+						remapbil,r360x180 \
+						"$file" \
+						"$out/$(basename "$file")"
+				done
+			done
 		done
 	done
 	;;
 
 calc_ensembles)
+	CPUS_TO_JOBS_FACTOR=4
 	mkdir -p data/ensembles
 	for list in "${LISTS_ENS[@]}"; do
-		cmd bin/calc_ensemble \
-			input/sources $(cat "sources/list/$list") \
-			data/ensembles
+		for freq in "${FREQS_ENS[@]}"; do
+			for var in "${VARS[@]}"; do
+				cmd bin/calc_ensemble \
+					"$freq" \
+					"$var" \
+					data/sources $(cat "sources/list/$list") \
+					data/ensembles
+			done
+		done
 	done
 	run
-	for file in data/ensembles/*; do
-		cmd ln -sf "../../data/ensembles/$(basename "$file")" -t input/sources
+	for file in data/ensembles/*/*/*/*.nc; do
+		path=${file#data/ensembles/}
+		dir=$(dirname "$path")
+		out=data/sources/$dir
+		mkdir -p "$out"
+		ln -sf "../../../../ensembles/$path" -t "$out/"
 	done
 	;;
 
 calc_stats)
 	for list in "${LISTS[@]}"; do
 		for subtype in "${SUBTYPES[@]}"; do
-			calc_stats input/sources \
+			calc_stats data/sources \
 				"$list" \
 				"$subtype" \
 				"data/stats/$list/$subtype"
 		done
 	done
 	for subtype in "${SUBTYPES[@]}"; do
-		calc_stats input/sources obs "$subtype" "data/stats/obs/$subtype"
+		calc_stats data/sources obs "$subtype" "data/stats/obs/$subtype"
 		calc_stats data/1deg obs "$subtype" "data/stats/obs_1deg/$subtype"
 	done
 	run
@@ -214,57 +389,33 @@ calc_stats)
 	done
 	;;
 
-calc_indices)
-	out=data/indices/tmp
-	mkdir -p "$out"
-	for list in "${LISTS_INDICES[@]}"; do
-		for source in $(cat "sources/list/$list"); do
-			for index in "${INDICES[@]}"; do
-				for file in "input/sources/$source"/*; do
-					echo cmd bin/climix -x "$index" "$file" "$out"
-				done
-			done
-		done
-	done
-	run
-	for file in "$out"/*; do
-		echo mv "$file" data/indices/$(bin/get_source_name "$out/$file")
-	done
-	;;
-
 plot_map_mean)
 	for list in "${LISTS_MAP_MEAN[@]}"; do
-		out=plot/map_mean/$list
-		mkdir -p "$out"
-		cmd bin/plot_map \
+		plot_map \
 			mean \
 			"data/stats/$list/period_season" \
-			$(cat sources/list/{obs,"$list"}) \
-			"$out"
+			"plot/map_mean/$list" \
+			$(cat sources/list/{obs,"$list"})
 	done
 	;;
 
 plot_map_trend)
 	for list in "${LISTS_MAP_TREND[@]}"; do
-		out=plot/map_trend/$list
-		mkdir -p "$out"
-		cmd bin/plot_map \
+		plot_map \
 			trend \
 			"data/stats/$list/period_season" \
-			$(cat sources/list/{obs,"${list}"}) \
-			"$out"
+			"plot/map_trend/$list" \
+			$(cat sources/list/{obs,"$list"})
 	done
 	;;
 
 plot_map_diff)
 	for list in "${LISTS_MAP_DIFF[@]}"; do
-		out=plot/map_diff/$list
-		mkdir -p "$out"
-		cmd bin/plot_map \
+		plot_map \
 			diff \
 			"data/stats/$list/period_season" \
-			$(cat "sources/list/$list") \
-			"$out"
+			"plot/map_diff/$list" \
+			$(cat "sources/list/$list")
 	done
 	;;
 
@@ -383,7 +534,7 @@ plot_gcm_rcm_tas)
 	;;
 
 download_topo)
-	wget -cO input/GMTED2010_mean_30arcsec.nc4 \
+	wget -cO data/GMTED2010_mean_30arcsec.nc4 \
 		'https://zenodo.org/records/14537811/files/GMTED2010_mean_30arcsec.nc4?download=1'
 	;;
 
@@ -392,12 +543,66 @@ remap_topo)
 	cmd cdo \
 		remapcon,r2880x1440 \
 		-sellonlatbox,-60,80,10,80 \
-		input/GMTED2010_mean_30arcsec.nc4 \
+		data/GMTED2010_mean_30arcsec.nc4 \
 		data/topo.nc
 	;;
 
 plot_domain_map)
 	cmd bin/plot_domain_map data/topo.nc plot/domain_map.pdf
+	;;
+
+calc_clim_indices)
+	CPUS_TO_JOBS_FACTOR=4
+	for list in "${LISTS_CLIM_INDICES[@]}"; do
+		for source in $(cat "sources/list/$list"); do
+			dir=data/sources/$source
+			for f in "$dir/day/tasmax/"*.nc; do
+				outdir=data/clim_indices/$source/yr/su
+				name=$(basename "$f")
+				out="$outdir/su_${name#*_}"
+				mkdir -p "$outdir"
+				cmd bin/calc_clim_index su "$f" "$out"
+			done
+			for f in "$dir/day/tas/"*.nc; do
+				outdir=data/clim_indices/$source/yr/gsstart
+				name=$(basename "$f")
+				out="$outdir/gsstart_${name#*_}"
+				mkdir -p "$outdir"
+				cmd bin/calc_clim_index gsstart "$f" "$out"
+			done
+		done
+	done
+	run
+	for file in data/clim_indices/*/*/*/*.nc; do
+		path=${file#data/clim_indices/}
+		dir=$(dirname "$path")
+		out=data/sources/$dir
+		mkdir -p "$out"
+		ln -sf "../../../../clim_indices/$path" -t "$out/"
+	done
+	;;
+
+archive)
+	rm -rf data/archive
+	out=data/archive
+	mkdir -p "$out"
+	ln -s "$(realpath input/landmask)" "$out/"
+	ln -s "$(realpath input/gcm_ecs_tcr.csv)" "$out/"
+	for list in "${LISTS_ARCHIVE[@]}"; do
+		for source in $(cat sources/list/{obs,"$list"}); do
+			[[ $source == EUR-12_ENS* ]] && continue
+			out=data/archive/sources/${source}_mon
+			mkdir -p "$out"
+			for var in "${ARCHIVE_VARS[@]}"; do
+				start=1991-01-01
+				end=2021-01-01
+				for f in "data/sources/${source}/mon/${var}"/*.nc; do
+					f=$(realpath "$f")
+					cmd "bin/has_time $start $end $f && ln -sf $f $out/"
+				done
+			done
+		done
+	done
 	;;
 
 *)
